# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59e62f6dfb4a0f121d64ca9096d3d0626302a1b3452ced69622785854456279d3caf1d9f7836812dc0e22b54ca9eae1b03c3786df3d04c42a71822e299b592f

test:
  secret_key_base: e2a817d24e231546dd70595edc4ff791e661bfae89945430ca15560c6d2d5152b0d1d64387ded46b859492219d5745215e0c3ecd30a91a0d2b4e086d12e6009e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
